update cicd

diff --git a/.github/workflows/autorelease.yml b/.github/workflows/autorelease.yml
--- a/.github/workflows/autorelease.yml
+++ b/.github/workflows/autorelease.yml
@@ -32,6 +32,12 @@ jobs:
             debian:bookworm \
             /bin/bash -c "/workspace/local/scripts/AutoCompile.sh"
 
+      - name: Check ISO exists
+        run: |
+          if [ ! -f live-image-amd64.hybrid.iso ]; then
+            echo "ISO build failed!"
+            exit 1
+          fi
       # Upload
       - name: Upload artifacts
         uses: actions/upload-artifact@v4
diff --git a/.github/workflows/manualbuild.yml b/.github/workflows/manualbuild.yml
--- a/.github/workflows/manualbuild.yml
+++ b/.github/workflows/manualbuild.yml
@@ -22,7 +22,12 @@ jobs:
             -w /workspace \
             debian:bookworm \
             /bin/bash -c "/workspace/local/scripts/AutoCompile.sh"
-
+      - name: Check ISO exists
+        run: |
+          if [ ! -f live-image-amd64.hybrid.iso ]; then
+            echo "ISO build failed!"
+            exit 1
+          fi
       - name: Upload artifacts
         uses: actions/upload-artifact@v4
         with:
