update cicd

diff --git a/.github/workflows/autorelease.yml b/.github/workflows/autorelease.yml
--- a/.github/workflows/autorelease.yml
+++ b/.github/workflows/autorelease.yml
@@ -24,17 +24,22 @@ jobs:
       - name: Build project in Docker container
         run: |
           chmod -R 777 gos-live
-          set -Eeuo pipefail
-          docker run --rm --privileged \
+          set -euo pipefail
+          sudo docker run --rm --privileged \
             -v ${{ github.workspace }}/gos-live:/workspace \
             -v /etc/timezone:/etc/timezone \
             -w /workspace \
-            debian:bookworm \
+            docker.m.daocloud.io/debian:bookworm \
             /bin/bash -c "/workspace/local/scripts/AutoCompile.sh"
-
+          last_line=$(awk 'NF{last=$0} END{print last}' gos-live/build.log | tr -d '\r')
+          echo "Last line: $last_line"
+          if [[ "$last_line" != "P: Build completed successfully" ]]; then
+            echo "::error::live-build did not complete successfully."
+            exit 1
+          fi
       - name: Check ISO exists
         run: |
-          if [ ! -f live-image-amd64.hybrid.iso ]; then
+          if [ ! -f gos-live/live-image-amd64.hybrid.iso ]; then
             echo "ISO build failed!"
             exit 1
           fi
diff --git a/.github/workflows/manualbuild.yml b/.github/workflows/manualbuild.yml
--- a/.github/workflows/manualbuild.yml
+++ b/.github/workflows/manualbuild.yml
@@ -22,9 +22,15 @@ jobs:
             -w /workspace \
             docker.m.daocloud.io/debian:bookworm \
             /bin/bash -c "/workspace/local/scripts/AutoCompile.sh"
+          last_line=$(awk 'NF{last=$0} END{print last}' gos-live/build.log | tr -d '\r')
+          echo "Last line: $last_line"
+          if [[ "$last_line" != "P: Build completed successfully" ]]; then
+            echo "::error::live-build did not complete successfully."
+            exit 1
+          fi
       - name: Check ISO exists
         run: |
-          if [ ! -f live-image-amd64.hybrid.iso ]; then
+          if [ ! -f gos-live/live-image-amd64.hybrid.iso ]; then
             echo "ISO build failed!"
             exit 1
           fi
